name: CI

on:
  push:
    branches: [main, development, feat-**, fix-**]
  
  pull_request:
    branches: [main, development]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv
      
      - name: Sync project
        run: uv sync

      - name: Ruff checks
        run: |
          uv run ruff format --check .
          uv run ruff check . 